- name: Prepare packaging variables
  contrail_packaging:
    zuul: "{{ zuul }}"

- name: Set container build dir
  set_fact:
    docker_build_dir: "{{ ansible_env.HOME }}/contrail-container-builder"

- name: Clone contrail-container-builder repository
  git:
    repo: 'https://github.com/Juniper/contrail-container-builder'
    force: yes
    dest: "{{ docker_build_dir }}"

- name: Prepare container build configuration
  copy:
    content: |
      CONTRAIL_VERSION={{ zuul.buildset }}-{{ zuul.patchset }}
      CONTRAIL_REGISTRY={{ site_pulp.fqdn }}
      CONTRAIL_REPOSITORY=http://{{ site_pulp.fqdn }}:{{ site_pulp.port }}/pulp/repos/{{ packaging.version.upstream }}-{{ zuul.change }}-{{ zuul.patchset }}
      OPENSTACK_VERSION=newton
    dest: "{{ docker_build_dir }}/common.env"

- name: Create log dir
  file: "path={{ docker_build_dir }}/logs state=directory"

- name: Build base containers
  include_tasks: build_container.yaml
  with_items:
  - base
  - analytics/base
  - controller/config/base
  - controller/control/base
  - controller/webui/base
  - test/base

- name: Build microservices
  include_tasks: build_container.yaml
  with_items:
  - agent/vrouter/
  - analytics/alarm-gen/
  - analytics/api/
  - analytics/collector/
  - analytics/query-engine/
  - analytics/snmp-collector/
  - analytics/topology/
  - controller/config/api/
  - controller/config/devicemgr/
  - controller/config/schema/
  - controller/config/svcmonitor/
  - controller/control/control/
  - controller/control/dns/
  - controller/control/named/
  - controller/webui/job/
  - controller/webui/web/
  - external/cassandra/
  - external/kafka/
  - external/rabbitmq/
  - external/zookeeper/
  - kubernetes/kube-manager/
  - kubernetes/vrouter-init/
  - nodemgr/
  - openstack/compute-contrail-backend/
  - openstack/neutron-contrail-backend/
  - test/newton/
